name: Branch Protection Issue
description: Reportar problemas con las protecciones de la rama main
title: "[PROTECCIÓN] "
labels: ["protection", "security"]
assignees:
  - GustavoEraso

body:
  - type: markdown
    attributes:
      value: |
        ## Protección de la rama main
        
        Usa este template para reportar problemas relacionados con las protecciones implementadas en la rama `main`.

  - type: dropdown
    id: issue-type
    attributes:
      label: Tipo de problema
      description: ¿Qué tipo de problema estás experimentando?
      options:
        - No puedo crear PR hacia main (esperado si no eres GustavoEraso)
        - Validaciones fallando incorrectamente
        - Problema con CODEOWNERS
        - Problema con workflows de GitHub Actions
        - Otro
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
      description: Describe detalladamente el problema que estás experimentando
      placeholder: Explica qué esperabas que pasara y qué está pasando en realidad
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: ¿Cómo podemos reproducir este problema?
      placeholder: |
        1. Intenté hacer...
        2. Ejecuté el comando...
        3. Vi el error...
    validations:
      required: false

  - type: input
    id: username
    attributes:
      label: Tu usuario de GitHub
      description: Tu nombre de usuario de GitHub
      placeholder: tu-usuario
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmación
      description: Por favor confirma que entiendes las protecciones implementadas
      options:
        - label: Entiendo que solo GustavoEraso puede crear PRs hacia la rama main
          required: true
        - label: He leído la documentación de protección en .github/BRANCH_PROTECTION.md
          required: true