name: Security Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Verify authorized user
      run: |
        if [ "${{ github.actor }}" != "GustavoEraso" ]; then
          echo "🚨 SECURITY ALERT: Unauthorized access attempt"
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          exit 1
        fi
        echo "✅ Security check passed for authorized user: ${{ github.actor }}"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check for sensitive files
      run: |
        echo "🔍 Checking for sensitive files..."
        
        # Check for common sensitive file patterns
        SENSITIVE_FILES=$(find . -name "*.env" -o -name "*.key" -o -name "*.pem" -o -name "*.p12" -o -name "*.pfx" 2>/dev/null | grep -v ".env.example" || true)
        
        if [ -n "$SENSITIVE_FILES" ]; then
          echo "⚠️  Warning: Potential sensitive files found:"
          echo "$SENSITIVE_FILES"
          echo "Please ensure these files don't contain real credentials"
        else
          echo "✅ No obvious sensitive files detected"
        fi

    - name: Check commit messages
      run: |
        echo "📝 Checking recent commit messages for security issues..."
        git log --oneline -5 | grep -i -E "(password|secret|key|token|credential)" && {
          echo "⚠️  Warning: Commit messages may contain sensitive information"
          echo "Please review commit messages for security"
        } || echo "✅ Commit messages look clean"

    - name: Security scan summary
      run: |
        echo "🛡️  Security scan completed"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Authorized user: ${{ github.actor }}"